In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
train_df = pd.read_csv("C:/Users/wmucd/Downloads/exploring-predictive-health-factors/PCOS_train.csv")

In [6]:
train_df.head()

ID    Age  Weight_kg PCOS Hormonal_Imbalance Hyperandrogenism Hirsutism  \
0   0  20-25       64.0   No                 No               No        No   
1   1  15-20       55.0   No                 No               No        No   
2   2  15-20       91.0   No                 No               No       Yes   
3   3  15-20       56.0   No                 No               No        No   
4   4  15-20       47.0   No                Yes               No        No   

  Conception_Difficulty Insulin_Resistance Exercise_Frequency  \
0                    No                 No             Rarely   
1                    No                 No   6-8 Times a Week   
2                    No                 No             Rarely   
3                    No                 No   6-8 Times a Week   
4                    No                 No             Rarely   

                               Exercise_Type     Exercise_Duration  \
0  Cardio (e.g., running, cycling, swimming)            30 minutes   
1                                No Exercise  Less than 30 minutes   
2  Cardio (e.g., running, cycling, swimming)  Less than 30 minutes   
3  Cardio (e.g., running, cycling, swimming)            45 minutes   
4                                No Exercise        Not Applicable   

         Sleep_Hours Exercise_Benefit  
0  Less than 6 hours         Somewhat  
1          6-8 hours         Somewhat  
2          6-8 hours         Somewhat  
3          6-8 hours       Not at All  
4          6-8 hours         Not Much

In [7]:
train_df.shape

(210, 14)

In [8]:
train_df.isnull().sum()

ID                       0
Age                      1
Weight_kg                2
PCOS                     0
Hormonal_Imbalance       2
Hyperandrogenism         3
Hirsutism                5
Conception_Difficulty    1
Insulin_Resistance       1
Exercise_Frequency       2
Exercise_Type            2
Exercise_Duration        2
Sleep_Hours              2
Exercise_Benefit         1
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

# List of columns to label encode
columns_to_encode = ['Age', 'Weight_kg', 'PCOS', 'Hormonal_Imbalance', 'Hyperandrogenism', 
                     'Hirsutism', 'Conception_Difficulty', 'Insulin_Resistance', 'Exercise_Frequency', 
                     'Exercise_Type', 'Exercise_Duration', 'Sleep_Hours', 'Exercise_Benefit']

# Initialize the LabelEncoder
le = LabelEncoder()


In [15]:
# Fill missing values with the mode (most frequent value) for each column
for col in columns_to_encode:
    train_df[col] = train_df[col].fillna(train_df[col].mode()[0])

# Display the DataFrame after filling missing values
print("After filling missing values:")
print(train_df[columns_to_encode].head())

After filling missing values:
     Age  Weight_kg PCOS Hormonal_Imbalance Hyperandrogenism Hirsutism  \
0  20-25       64.0   No                 No               No        No   
1  15-20       55.0   No                 No               No        No   
2  15-20       91.0   No                 No               No       Yes   
3  15-20       56.0   No                 No               No        No   
4  15-20       47.0   No                Yes               No        No   

  Conception_Difficulty Insulin_Resistance Exercise_Frequency  \
0                    No                 No             Rarely   
1                    No                 No   6-8 Times a Week   
2                    No                 No             Rarely   
3                    No                 No   6-8 Times a Week   
4                    No                 No             Rarely   

                               Exercise_Type     Exercise_Duration  \
0  Cardio (e.g., running, cycling, swimming)            30 minut

In [17]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each column in the list
for col in columns_to_encode:
    train_df[col] = le.fit_transform(train_df[col])

# Display the unique values after encoding for each column
encoded_values = {col: train_df[col].unique() for col in columns_to_encode}
print("After applying LabelEncoder:")
print(encoded_values)


After applying LabelEncoder:
{'Age': array([1, 0, 7, 4, 6, 2, 8, 3, 5, 9]), 'Weight_kg': array([37, 28, 56, 29, 16, 10, 31, 54, 44, 35, 48, 41, 39,  2, 45, 21, 22,
       17, 46, 24, 26,  7, 19, 55, 30, 58, 13, 12, 40, 14, 32, 20, 36, 15,
       43,  9, 33, 38, 18, 42,  5, 51, 34, 23,  8, 11, 52, 49,  4, 47, 27,
       53, 57,  1, 50,  6,  3,  0, 25], dtype=int64), 'PCOS': array([0, 1]), 'Hormonal_Imbalance': array([0, 2, 1, 3]), 'Hyperandrogenism': array([0, 1]), 'Hirsutism': array([0, 2, 1]), 'Conception_Difficulty': array([0, 3, 1, 2]), 'Insulin_Resistance': array([0, 2, 1]), 'Exercise_Frequency': array([7, 2, 6, 0, 1, 3, 5, 4]), 'Exercise_Type': array([ 1, 10,  4,  7,  9,  2,  5, 15, 14,  8,  3,  0, 12, 13, 11,  6]), 'Exercise_Duration': array([1, 4, 3, 7, 6, 0, 5, 2]), 'Sleep_Hours': array([3, 1, 2, 4, 0]), 'Exercise_Benefit': array([2, 1, 0, 3])}


In [19]:
train_df.isnull().sum()

ID                       0
Age                      0
Weight_kg                0
PCOS                     0
Hormonal_Imbalance       0
Hyperandrogenism         0
Hirsutism                0
Conception_Difficulty    0
Insulin_Resistance       0
Exercise_Frequency       0
Exercise_Type            0
Exercise_Duration        0
Sleep_Hours              0
Exercise_Benefit         0
dtype: int64

In [21]:
train_feature = train_df.drop(['ID', 'PCOS'], axis=1)  # Drop 'ID' and 'PCOS' from features
train_label = train_df['PCOS']  # Target variable


In [23]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(train_feature, train_label)


RandomForestClassifier(random_state=42)

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
test_df = pd.read_csv("C:/Users/wmucd/Downloads/exploring-predictive-health-factors/PCOS_test.csv")

In [27]:
test_df.head()

ID           Age  Weight_kg Hormonal_Imbalance Hyperandrogenism Hirsutism  \
0   0         20-25       54.0                 No               No        No   
1   1         20-25       65.0                Yes               No        No   
2   2         20-25       64.0                Yes               No        No   
3   3  Less than 20       57.0                Yes               No       Yes   
4   4  Less than 20        6.0                Yes               No       Yes   

  Conception_Difficulty Insulin_Resistance Exercise_Frequency Exercise_Type  \
0                    No                 No             Rarely   No Exercise   
1                    No                 No   3-4 Times a Week   No Exercise   
2                    No                 No   6-8 Times a Week  Cardio (e.g.   
3                    No                Yes             Rarely   No Exercise   
4                    No                 No             Rarely  Cardio (e.g.   

      Exercise_Duration Sleep_Hours Exercise_Benefit  
0  Less than 30 minutes   6-8 hours         Somewhat  
1        Not Applicable   6-8 hours         Somewhat  
2        Not Applicable   6-8 hours         Somewhat  
3             6-8 hours   6-8 hours         Somewhat  
4            30 minutes   6-8 hours         Somewhat

In [29]:
test_df.shape

(145, 13)

In [31]:
test_df.isnull().sum()

ID                       0
Age                      1
Weight_kg                2
Hormonal_Imbalance       3
Hyperandrogenism         1
Hirsutism                2
Conception_Difficulty    2
Insulin_Resistance       1
Exercise_Frequency       1
Exercise_Type            1
Exercise_Duration        0
Sleep_Hours              1
Exercise_Benefit         1
dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder

# List of columns to label encode
columns_to_encode_test = ['Age', 'Weight_kg','Hormonal_Imbalance', 'Hyperandrogenism', 
                     'Hirsutism', 'Conception_Difficulty', 'Insulin_Resistance', 'Exercise_Frequency', 
                     'Exercise_Type', 'Exercise_Duration', 'Sleep_Hours', 'Exercise_Benefit']

# Initialize the LabelEncoder
le = LabelEncoder()

In [35]:
# Fill missing values with the mode (most frequent value) for each column
for col in columns_to_encode_test:
    test_df[col] = test_df[col].fillna(test_df[col].mode()[0])

# Display the DataFrame after filling missing values
print("After filling missing values:")
print(test_df[columns_to_encode_test].head())

After filling missing values:
            Age  Weight_kg Hormonal_Imbalance Hyperandrogenism Hirsutism  \
0         20-25       54.0                 No               No        No   
1         20-25       65.0                Yes               No        No   
2         20-25       64.0                Yes               No        No   
3  Less than 20       57.0                Yes               No       Yes   
4  Less than 20        6.0                Yes               No       Yes   

  Conception_Difficulty Insulin_Resistance Exercise_Frequency Exercise_Type  \
0                    No                 No             Rarely   No Exercise   
1                    No                 No   3-4 Times a Week   No Exercise   
2                    No                 No   6-8 Times a Week  Cardio (e.g.   
3                    No                Yes             Rarely   No Exercise   
4                    No                 No             Rarely  Cardio (e.g.   

      Exercise_Duration Sleep_Hours Ex

In [37]:
test_df["ID"].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144], dtype=int64)

In [39]:
from sklearn.preprocessing import LabelEncoder
le_ID = LabelEncoder()
test_df['ID'] = le_ID.fit_transform(test_df['ID'])
test_df["ID"].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144], dtype=int64)

In [41]:
from sklearn.preprocessing import LabelEncoder
le_Age = LabelEncoder()
test_df['Age'] = le_Age.fit_transform(test_df['Age'])
test_df["Age"].unique()

array([ 1, 10,  7, 12,  4, 11,  5,  3,  9,  2,  0,  6,  8])

In [43]:
from sklearn.preprocessing import LabelEncoder
le_Weight_kg = LabelEncoder()
test_df['Weight_kg'] = le_Weight_kg.fit_transform(test_df['Weight_kg'])
test_df["Weight_kg"].unique()

array([18, 29, 28, 21,  0, 19, 20, 10, 33, 11, 24,  2, 15, 13, 23, 12,  9,
       14, 32,  8, 30, 16, 31, 22,  1, 17, 27, 34,  5, 26, 25,  4, 35,  6,
        3,  7, 36, 37], dtype=int64)

In [45]:
from sklearn.preprocessing import LabelEncoder
le_Hormonal_Imbalance = LabelEncoder()
test_df['Hormonal_Imbalance'] = le_Hormonal_Imbalance.fit_transform(test_df['Hormonal_Imbalance'])
test_df["Hormonal_Imbalance"].unique()

array([0, 1])

In [47]:
from sklearn.preprocessing import LabelEncoder
le_Hyperandrogenism = LabelEncoder()
test_df['Hyperandrogenism'] = le_Hyperandrogenism.fit_transform(test_df['Hyperandrogenism'])
test_df["Hyperandrogenism"].unique()

array([0, 1])

In [49]:
from sklearn.preprocessing import LabelEncoder
le_Hirsutism = LabelEncoder()
test_df['Hirsutism'] = le_Hirsutism.fit_transform(test_df['Hirsutism'])
test_df["Hirsutism"].unique()

array([0, 1])

In [51]:
from sklearn.preprocessing import LabelEncoder
le_Conception_Difficulty = LabelEncoder()
test_df['Conception_Difficulty'] = le_Conception_Difficulty.fit_transform(test_df['Conception_Difficulty'])
test_df["Conception_Difficulty"].unique()

array([0, 2, 1])

In [53]:
from sklearn.preprocessing import LabelEncoder
le_Insulin_Resistance = LabelEncoder()
test_df['Insulin_Resistance'] = le_Insulin_Resistance.fit_transform(test_df['Insulin_Resistance'])
test_df["Insulin_Resistance"].unique()

array([0, 1, 2])

In [55]:
from sklearn.preprocessing import LabelEncoder
le_Exercise_Frequency = LabelEncoder()
test_df['Exercise_Frequency'] = le_Exercise_Frequency.fit_transform(test_df['Exercise_Frequency'])
test_df["Exercise_Frequency"].unique()

array([10,  2,  4,  9,  0,  8,  7,  3,  6, 11,  5,  1])

In [57]:
from sklearn.preprocessing import LabelEncoder
le_Exercise_Type = LabelEncoder()
test_df['Exercise_Type'] = le_Exercise_Type.fit_transform(test_df['Exercise_Type'])
test_df["Exercise_Type"].unique()

array([ 3,  0,  8,  9, 10,  1,  2,  5,  4,  6,  7])

In [59]:
from sklearn.preprocessing import LabelEncoder
le_Exercise_Duration = LabelEncoder()
test_df['Exercise_Duration'] = le_Exercise_Duration.fit_transform(test_df['Exercise_Duration'])
test_df["Exercise_Duration"].unique()

array([ 8, 10,  6,  3,  1,  9,  7,  4,  2, 11,  0,  5])

In [61]:
from sklearn.preprocessing import LabelEncoder
le_Sleep_Hours = LabelEncoder()
test_df['Sleep_Hours'] = le_Sleep_Hours.fit_transform(test_df['Sleep_Hours'])
test_df["Sleep_Hours"].unique()

array([4, 5, 6, 3, 1, 2, 0])

In [63]:
from sklearn.preprocessing import LabelEncoder
le_Exercise_Benefit = LabelEncoder()
test_df['Exercise_Benefit'] = le_Exercise_Benefit.fit_transform(test_df['Exercise_Benefit'])
test_df["Exercise_Benefit"].unique()

array([2, 1, 3, 0])

In [67]:
test_feature = test_df.drop(columns=['ID'])

In [69]:
# Get predicted probabilities (for the positive class, i.e., PCOS=1)
y_pred_prob = model.predict_proba(test_feature)[:, 1]


In [71]:
y_pred_prob

array([0.04, 0.01, 0.02, 0.15, 0.46, 0.03, 0.03, 0.08, 0.04, 0.05, 0.  ,
       0.03, 0.04, 0.07, 0.04, 0.33, 0.09, 0.13, 0.07, 0.28, 0.09, 0.07,
       0.11, 0.15, 0.01, 0.02, 0.54, 0.01, 0.02, 0.08, 0.07, 0.03, 0.04,
       0.03, 0.12, 0.08, 0.41, 0.07, 0.03, 0.15, 0.05, 0.06, 0.15, 0.05,
       0.09, 0.41, 0.15, 0.38, 0.16, 0.25, 0.12, 0.01, 0.08, 0.36, 0.1 ,
       0.4 , 0.31, 0.39, 0.02, 0.06, 0.  , 0.03, 0.03, 0.17, 0.  , 0.44,
       0.14, 0.06, 0.02, 0.06, 0.06, 0.3 , 0.09, 0.08, 0.03, 0.03, 0.08,
       0.05, 0.02, 0.04, 0.27, 0.11, 0.04, 0.14, 0.04, 0.07, 0.02, 0.07,
       0.04, 0.06, 0.08, 0.12, 0.13, 0.02, 0.07, 0.03, 0.09, 0.04, 0.01,
       0.04, 0.19, 0.02, 0.  , 0.14, 0.13, 0.37, 0.14, 0.16, 0.03, 0.14,
       0.46, 0.38, 0.1 , 0.1 , 0.01, 0.03, 0.  , 0.02, 0.02, 0.04, 0.18,
       0.06, 0.02, 0.02, 0.35, 0.07, 0.06, 0.42, 0.03, 0.01, 0.04, 0.06,
       0.11, 0.07, 0.11, 0.04, 0.07, 0.09, 0.21, 0.06, 0.06, 0.04, 0.49,
       0.2 , 0.  ])

In [73]:
# Add predicted PCOS probability as a new column in test_df
test_df['PCOS'] = y_pred_prob

In [75]:
test_df

ID  Age  Weight_kg  Hormonal_Imbalance  Hyperandrogenism  Hirsutism  \
0      0    1         18                   0                 0          0   
1      1    1         29                   1                 0          0   
2      2    1         28                   1                 0          0   
3      3   10         21                   1                 0          1   
4      4   10          0                   1                 0          1   
..   ...  ...        ...                 ...               ...        ...   
140  140    1         16                   1                 0          0   
141  141    1         31                   0                 0          0   
142  142    1         19                   1                 1          1   
143  143   10         13                   0                 0          1   
144  144    1         19                   1                 0          0   

     Conception_Difficulty  Insulin_Resistance  Exercise_Frequency  \
0                        0                   0                  10   
1                        0                   0                   2   
2                        0                   0                   4   
3                        0                   1                  10   
4                        0                   0                  10   
..                     ...                 ...                 ...   
140                      0                   0                  10   
141                      0                   0                  10   
142                      2                   0                  10   
143                      0                   0                   1   
144                      0                   0                   0   

     Exercise_Type  Exercise_Duration  Sleep_Hours  Exercise_Benefit  PCOS  
0                3                  8            4                 2  0.04  
1                3                 10            4                 2  0.01  
2                0                 10            4                 2  0.02  
3                3                  6            4                 2  0.15  
4                0                  3            4                 2  0.46  
..             ...                ...          ...               ...   ...  
140              0                  8            4                 2  0.06  
141              9                  8            4                 1  0.04  
142              0                  7            4                 3  0.49  
143              0                  8            4                 0  0.20  
144              1                  8            4                 2  0.00  

[145 rows x 14 columns]

In [77]:
from sklearn.preprocessing import LabelEncoder
le_PCOS = LabelEncoder()
test_df['PCOS'] = le_PCOS.fit_transform(test_df['PCOS'])
test_df["PCOS"].unique()

array([ 4,  1,  2, 15, 37,  3,  8,  5,  0,  7, 27,  9, 13, 24, 11, 39, 12,
       34,  6, 31, 16, 22, 29, 10, 33, 26, 32, 17, 36, 14, 25, 23, 19, 30,
       18, 28, 35, 21, 38, 20], dtype=int64)

In [79]:
# Convert probability to binary prediction (threshold = 0.5)
test_df['PCOS_Predicted'] = (test_df['PCOS'] > 0.5).astype(int)

In [81]:
# Display the updated test dataframe
print("Test dataset with predictions:")
print(test_df.head())

Test dataset with predictions:
   ID  Age  Weight_kg  Hormonal_Imbalance  Hyperandrogenism  Hirsutism  \
0   0    1         18                   0                 0          0   
1   1    1         29                   1                 0          0   
2   2    1         28                   1                 0          0   
3   3   10         21                   1                 0          1   
4   4   10          0                   1                 0          1   

   Conception_Difficulty  Insulin_Resistance  Exercise_Frequency  \
0                      0                   0                  10   
1                      0                   0                   2   
2                      0                   0                   4   
3                      0                   1                  10   
4                      0                   0                  10   

   Exercise_Type  Exercise_Duration  Sleep_Hours  Exercise_Benefit  PCOS  \
0              3                  8    

In [83]:
# Create output DataFrame with 'ID' and 'PCOS'
output = pd.DataFrame({'ID': test_df['ID'], 'PCOS': y_pred_prob})

# Save to CSV file
output.to_csv("sample_submission6.csv", index=False)

print("Predictions saved to sample_submission.csv")

Predictions saved to sample_submission.csv


In [85]:
x = np.array([["20-25", "54", "No", "No", "No", "No", "No", "Rarely", "No Exercise", "Less than 30 minutes", "6-8 hours", "Somewhat"]])
x

array([['20-25', '54', 'No', 'No', 'No', 'No', 'No', 'Rarely',
        'No Exercise', 'Less than 30 minutes', '6-8 hours', 'Somewhat']],
      dtype='<U20')

In [87]:
x[:, 0] = le_Age.fit_transform(x[:, 0])
x[:, 1] = le_Weight_kg.fit_transform(x[:, 1])
x[:, 2] = le_Hormonal_Imbalance .fit_transform(x[:, 2])
x[:, 3] = le_Hyperandrogenism .fit_transform(x[:, 3])
x[:, 4] = le_Hirsutism .fit_transform(x[:, 4])
x[:, 5] = le_Conception_Difficulty .fit_transform(x[:, 5])
x[:, 6] = le_Insulin_Resistance .fit_transform(x[:, 6])
x[:, 7] = le_Exercise_Frequency.fit_transform(x[:, 7])
x[:, 8] = le_Exercise_Type.fit_transform(x[:, 8])
x[:, 9] = le_Exercise_Duration .fit_transform(x[:, 9])
x[:, 10] = le_Sleep_Hours .fit_transform(x[:, 10])
x[:, 11] = le_Exercise_Benefit .fit_transform(x[:, 11])

x

array([['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']],
      dtype='<U20')

In [91]:
regressor = RandomForestClassifier

In [93]:
import pickle

data_to_save = {
    "model": regressor,
    "le_Age": le_Age,
    "le_Weight_kg": le_Weight_kg,
    "le_Hormonal_Imbalance": le_Hormonal_Imbalance,
    "le_Hyperandrogenism": le_Hyperandrogenism,
    "le_Hirsutism": le_Hirsutism,
    "le_Conception_Difficulty": le_Conception_Difficulty,
    "le_Insulin_Resistance": le_Insulin_Resistance,
    "le_Exercise_Frequency": le_Exercise_Frequency,
    "le_Exercise_Type":le_Exercise_Type,
    "le_Exercise_Duration": le_Exercise_Duration,
    "le_Sleep_Hours": le_Sleep_Hours,
    "le_Exercise_Benefit":le_Exercise_Benefit
}

with open('PCOS.pkl', 'wb') as file:
    pickle.dump(data_to_save, file)

print("File saved successfully.")

File saved successfully.
